### ISSUE TITLE
[Missing ontology] NCIT

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#10]
Ontology is available at: http://www.ontobee.org/ontology/NCIT

#### Reasons for this addition
NCI Thesaurus OBO Edition supposedly covers many terms specifically required for submission to NCBI repositories.

**Comment by kdumschott** [comment]
http://purl.obolibrary.org/obo/ncit.obo has been added to the ext_ontologies.include list and will now be added to SwateDB
