### ISSUE TITLE
Add rules for adding new terms

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#18]
@HajiraJabeen had a really nice slide in her latest presentation with rules on how to add new terms/ontologies. It would be nice to have these rules in the README.md of this repo.

**Comment by Freymaurer** [comment]
i refer to this slide:
![image](https://user-images.githubusercontent.com/39732517/138161102-48ae5a2a-aa25-4c66-a9b2-63096534250a.png)

**Comment by kdumschott** [comment]
The README.md has been updated with the rules for adding new terms, including the new issues templates
