### ISSUE TITLE
[Import term(s)]http://purl.obolibrary.org/obo/BTO_0001900

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/nfdi4plants_ontology#28]
Term accession number(s):BTO_0001900
and children
#### Reasoning
Please provide short reasoning why to import these terms
Needed to decribe growth phase of suspension cultures please also provide children to describe growth phase

**Comment by kdumschott** [comment]
BTO_0001900 and child terms have now been added to DPBO.
