### ISSUE TITLE
[Import term(s)]http://purl.obolibrary.org/obo/EO_0001001

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/nfdi4plants_ontology#29]
Term accession number(s):EO_0001001
AND CHILDREN

#### Reasoning
important terms to describe plant abiotic stress application which i cannot fiind in the recent vocabulary
e.g. temperature regime, salt ttreatment etc.

**Comment by kdumschott** [comment]
The Plant Environment Ontology (EO) as been deprecated so it is no longer possible to import terms directly from the ontology. Two options for using these terms are as follows:

1. The EFO has imported these terms into their ontology. As EFO is included in SwateDB, it is possible to use these exact terms (with EO ids) in Swate.

2. According to https://obofoundry.org/ontology/eo.html, "If you are using classes like EO:nnnnnn then you should be able to substitute this for PECO:nnnnnn, as all of the numeric parts of the ID are preserved." PECO is also in SwateDB so the terms should already be included in Swate. Please note: the PECO term labels are slightly changed (for example, the EO_0001001 term label is 'plant treatment' whereas the PECO_0001001 term label is 'plant exposure').
