### ISSUE TITLE
nfdi4pso should not contain a number?

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#33]
While working on Swate i was presented with a [link](https://obofoundry.org/id-policy), showing defined parsing options for IDSPACE and LOCALID in term accessions. The below text comes from the original issue and shows the code example and explains subparts of it. tl;dr according to the official docs IDSPACE MUST NOT contain a number, but `nfdi4pso` contains a number. What should we do here?

---

From the code shown here `s@((**[A-Za-z_]***):(d+))@http://purl.obolibrary.org/obo/$1_$2@`: 

- **IDSPACE** must be a letter OR an underscore ([A-Za-z_]).
- **LOCALID** must be any number (d+).

This does not look good for our nfdi4pso.

@muehlhaus maybe this should be a discussion point on future meetings. For now i will keep numbers in the swate internal parsing.

_Originally posted by @Freymaurer in https://github.com/nfdi4plants/Swate/issues/210#issuecomment-1173739558_

**Comment by kdumschott** [comment]
The ontology namespace has been changed to dpbo
