### ISSUE TITLE
[SWATH-MS protein profiling assay] 

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/nfdi4plants_ontology#35]
### Term name and id

BAO_0010026

and some children

### Term link

http://www.bioassayontology.org/bao#BAO_0010026

### Parent term(s)

could go somewhere to Mass spectrometry 

### Child term(s)

Yes_
- [protein profiling assay](https://ontobee.org/ontology/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0010026)
+ [shotgun MS protein profiling assay](https://ontobee.org/ontology/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0010027)
+ [SWATH MS protein profiling assay](https://ontobee.org/ontology/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0010028)
- [Tandem Mass Tag (TMT) MS Protein Quantification](https://ontobee.org/ontology/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0010070)
- [Liquid Chromatography/Mass Spectroscopy (LC/MS) protein quantification](https://ontobee.org/ontology/BAO?iri=http://www.bioassayontology.org/bao%23BAO_0010071)

### Please state the reason to import this term into nfdi4pso

cool terms fpr proteomics and metabolomics Mass spec
need thees or find better ones for data independent acquisition

**Comment by kdumschott** [comment]
BAO:0010026 and all children have been imported into dpbo.
