### ISSUE TITLE
Swate selecting values from xref ++ is_a / has_participant 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#38]
Hey, I've spotted a small "xref" issue with terms and "is_a" instances selectable from within SWATE (term-directed search). 

For example: 
The term DPBO:0000040 (used to be NFDI4PSO:0000040) has some child terms required for "next generation sequencing instrument model" to comply with e.g. GEO requirements. However, using the term-directed search yields a lot of sequencing techniques (DNA-seq, ChIP-Seq, etc.) rather than instruments. 

```
[Term]
id: DPBO:0000040
name: next generation sequencing instrument model
def: "Model name or number of next generation sequencing instrument" []
xref: EFO:0003739
```

The term is xref'ed to "EFO:0003739" (sequencer) https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0003739 and if I understand the panel on the right correctly, those techniques come from the "has_participant" relationship?

**Comment by Brilator** [comment]
@Freymaurer @Zerskk 
Linking you here since this might be an issue how Swate / SwateDB handles xref and is_a?

**Comment by Freymaurer** [comment]
I tried looking for child terms in swate and get exactly these instrument models?

![image](https://user-images.githubusercontent.com/39732517/202484605-9573523c-aa00-41cc-9186-682973f7dfb8.png)

Can you give me the use case where this behaves unexpected?

**Comment by Brilator** [comment]
Sorry, my bad. the behavior happened on the obsolete term NFDI4PSO:0000040. So it relates somewhat to #39 

<img width="1721" alt="Screen Shot 2022-11-17 at 16 18 07" src="https://user-images.githubusercontent.com/16229676/202485826-2710e9f6-9129-4580-944a-11fcfcae801b.png">

**Comment by Freymaurer** [comment]
In my opinion we should close this issue then and just work on not showing obsolete nfdi4pso/dpbo terms in the search results 👍  If you are okay with this @Brilator

**Comment by Brilator** [comment]
true
