### ISSUE TITLE
Duplicate information terms from previous xref workflow

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#41]
When importing external terms for usage in the SwateDB the previous workflow was to create a "duplicate" nfdi4pso/dpbo term with an xref to the source term. Now we do not want to use this workflow anymore but we still have leftover terms from this practise in our ontology.

```
[Term]
id: DPBO:0000068
name: cell line
def: "A permanently established cell culture that will proliferate indefinitely given appropriate fresh medium and space. [ NCI On-line Medical Dictionary ] " []
comment: “[Definition Source: http://purl.obolibrary.org/obo/NCIT_C16403]"
xref: NCIT:C16403
```

https://github.com/nfdi4plants/nfdi4plants_ontology/blob/a9031e12ecd682ce58ff41f93b4070912d9cd442/dpbo.obo#L539

These should be made obsolete.

**Comment by kdumschott** [comment]
I will do a pass through and remove/obsolete all terms that fit this criteria.
