### ISSUE TITLE
Terms from unit ontology imported

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#42]
We have terms from the unit ontology in the dpbo.

```
[Term]
id: UO:0000000
name: unit
namespace: unit.ontology
def: "A unit of measurement is a standardized quantity of a physical quality." [Wikipedia:Wikipedia]
created_by: george gkoutos

[Term]
id: UO:0000048
name: acceleration unit
namespace: unit.ontology
def: "A unit which is a standard measure of the rate of change of velocity in either speed or direction." [Wikipedia:Wikipedia]
subset: unit_group_slim
is_a: UO:0000000 ! unit
created_by: george gkoutos
```

There is, as far as i can see, no new information added with these terms (no new relationships) AND we already add the unit ontology in `ext_ontologies.include`. So these should be removed.

https://github.com/nfdi4plants/nfdi4plants_ontology/blob/a9031e12ecd682ce58ff41f93b4070912d9cd442/dpbo.obo#L2421

**Comment by kdumschott** [comment]
There are new relationships added under acceleration unit. The following DPBO terms are added as subclasses under unit>acceleration unit. I did this in order to add semantic context to the terms.
```
[Term]
id: DPBO:0000083
name: relative centrifugal force
def: "Relative centrifugal force (RCF) is the amount of force applied to a sample when using a centrifuge. It is dependant on the speed of the centrifuge rotation as well as the distance of the sample from the center of rotation." []
synonym: "RCF" EXACT []
is_a: UO:0000048 ! acceleration unit
equivalent_to: DPBO:0000084 ! g-force

[Term]
id: DPBO:0000084
name: g-force
def: "G-force is the force acting on an object as a result of acceleration or gravity." []
is_a: UO:0000048 ! acceleration unit

[Term]
id: DPBO:0000085
name: standard gravity
def: "The standard acceleration of an object in free fall at or near sea level equivalent to 9.807 m/s2." []
synonym: "g0" EXACT []
synonym: "standard acceleration due to gravity" EXACT []
synonym: "standard acceleration of free fall" EXACT []
is_a: UO:0000048 ! acceleration unit
```

What I suggest is removing UO:000048 (acceleration unit) for now as the likeliest Swate column heading for these terms would be 'unit'. I can always add it again later if we need it. Please let me know if this is an agreeable solution.

**Comment by Freymaurer** [comment]
`UO:000048 (acceleration unit)` will not be removed as we include the whole unit ontology. Maybe ask @Brilator how to handle this case. I do not know if what users will expect when looking for this term.

**Comment by kdumschott** [comment]
Yes, UO is included in the SwateDB, so the term itself will not be removed from Swate. I was referring to removing the term from dpbo.obo, which will remove the is_a relationships between ``UO:000048 (acceleration unit)`` and dpbo child terms.
