### ISSUE TITLE
[Import Ontology]  PPEO

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/nfdi4plants_ontology#43]
### Ontology

Plant Phenotype Experiment Ontology

### Please state the reason to import this ontology into the SwateDB

Ontology for describing plant phenytyping experiments (Implementation of MIAPPE)

URI:

http://agroportal.lirmm.fr/ontologies/PPEO

https://raw.githubusercontent.com/MIAPPE/MIAPPE-ontology/master/PPEO.owl

**Comment by kdumschott** [comment]
Hi there Angela, do you have an obo file for the PPEO? I took a look but don't see one (only owl). Currently, we are only able to add external ontologies as obo files. 

Or @Zerskk, is there a workflow for converting owl files to obo for Swobup?

**Comment by Zerskk** [comment]
we do not currently support owl files. But as a workaround, an owl file can be converted to obo and placed in the repository. Swobup will then discover the obo file and import the ontology into the database.

**Comment by kdumschott** [comment]
The converted PPEO.owl as been added to the repository.

**Comment by kdumschott** [comment]
Due to errors that occur when converting from OWL to OBO, the PPEO ontology had to be manually built. It can be found in the miappe.obo file. Please be aware that this is not the actual PPEO ontology and that a differnt namespace (miappe) was used for the terms.
