### ISSUE TITLE
[Import Ontology] Credit ontology

### ISSUE THREAD

**Issue by Hannah-Doerpholz** [nfdi4plants/nfdi4plants_ontology#46]
### Ontology

http://purl.org/credit/releases/2019-04-11/credit.owl

### Please state the reason to import this ontology into the SwateDB

It was mentioned by the MIAPPE team at the Biohackathon Germany that it would be beneficial to include the credit ontology in out database. It contains many terms that can be used to fill the ISA field "role" (in the person schema). The ontology contains more terms to accurately describe a person's role within an investigation or study and provides more terms than are currently in the database. 

Unfortunately, on their own website and on ontobee only the owl version is published. However, there is an obo version on github which should be the one to be imported. The github link is the following:

https://github.com/data2health/credit-ontology/blob/master/credit.obo

**Comment by kdumschott** [comment]
done!
