### ISSUE TITLE
[Import term] Quantification method from PRIDE

### ISSUE THREAD

**Issue by Martin-Kuhl** [nfdi4plants/nfdi4plants_ontology#47]
### Term name and id

Quantification method (PRIDE_0000307)

### Term link

http://purl.obolibrary.org/obo/PRIDE_0000307

### Child term(s)

The following child terms are desirable so that they can directly be used for PRIDE submission.

![ChildTerms](https://user-images.githubusercontent.com/87656451/207622166-0e3ec175-a04b-4300-a424-86cdacb13b3d.jpg)

### Please state the reason to import this term into dpbo

Terms are needed for creation of a template and subsequent submission to the PRIDE repository, as they have their own CV.

### Your ORCID

0000-0002-8493-1077

**Comment by kdumschott** [comment]
Quantification method and child terms have been imported to dpbo.
