### ISSUE TITLE
MS missing from ontobee 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#50]
### Type of Issue

- [X] Report a Bug
- [ ] Report a Typo or Error
- [ ] Feature Request
- [ ] Help or Question

### Comments

The links (e.g. in Swate) to MS ontology run into missing terms (e.g. http://www.ontobee.org/ontology/MS?iri=http://purl.obolibrary.org/obo/MS_1000031) 

Might need to contact ontobee people. 

MS ontology is there, but odd: https://ontobee.org/ontology/MS

**Comment by kdumschott** [comment]
This was originally reported in https://github.com/nfdi4plants/Swate/issues/241 has already been reported to Ontobee (https://github.com/OntoZoo/ontobee/issues/185#issue-1476421013)

**Comment by Brilator** [comment]
oops, sorry
