### ISSUE TITLE
[Import term] grinding

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#52]
### Term name and id

grinding CHMO:0001652

### Term link

http://purl.obolibrary.org/obo/CHMO_0001652

### Parent term(s)

material processing (OBI:0000094)

### Please state the reason to import this term into dpbo

Common process to prepare samples for extraction of bio entities like DNA, RNA, metabolites etc.

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term has been imported into dpbo.
