### ISSUE TITLE
[Import term] vacuum drying

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#54]
### Term name and id

vacuum drying CHMO:0001557

### Term link

http://purl.obolibrary.org/obo/CHMO_0001557

### Parent term(s)

material processing (OBI:0000094)

### Please state the reason to import this term into dpbo

Commonly done for metabolite extracts before resuspension for GC/LC-MS.

Should be child term of sample drying (CHMO:0001549)

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term has been imported into dpbo.
