### ISSUE TITLE
[Import term] trimethylsilyl derivatisation

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#56]
### Term name and id

trimethylsilyl derivatisation CHMO:0002758

### Term link

http://purl.obolibrary.org/obo/CHMO_0002758

### Parent term(s)

material processing (OBI:000009), MS derivatization (DPBO:0000052)

### Please state the reason to import this term into dpbo

Common derivatization method for GC-MS.

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term has been imported into dpbo.
