### ISSUE TITLE
[Synonym] derivatization

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#57]
### dpbo term

MS derivatization DPBO:0000052

### Synonym to be added

derivatization (CHMO:0001485)

### Scope

NARROW

### Comments

This could be added as synonym and adapted to CHMO ontology. Here it is under the parent term material processing and then derivatization terms could be added below as child terms. See CHMO ontology: https://www.ebi.ac.uk/ols/ontologies/chmo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHMO_0002758&lang=en&viewMode=All&siblings=false

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term has been imported into dpbo.
