### ISSUE TITLE
[Import term] Thinning

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#60]
### Term name and id

Thinning (AGRO:00000027)

### Term link

http://purl.obolibrary.org/obo/AGRO_00000027

### Please state the reason to import this term into dpbo

Could be used to describe when plant parts are removed during an experiment (e.g. diseased, senescent). Could be child term of pruning (see issue #59).

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term was added to dpbo.
