### ISSUE TITLE
[Import term] desuckering

### ISSUE THREAD

**Issue by micwij** [nfdi4plants/nfdi4plants_ontology#61]
### Term name and id

desuckering (AGRO:00000007)

### Term link

http://purl.obolibrary.org/obo/AGRO_00000007

### Please state the reason to import this term into dpbo

Useful term to describe the removal of axillary buds in larger plants like tomato. Could be child term to thinning (see issue #60 ) according to the AGRO ontology.

### Your ORCID

0000-0003-3393-4224

**Comment by kdumschott** [comment]
Thank you for your contribution, the suggested term was added to dpbo.
