### ISSUE TITLE
Confusion over bio vs. arc/container ontology?

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#64]
Just stumbled across a few terms, that I think are covered by ISA / ARC ontology.
Not sure about a solution, but would probably need xref them. 

```
[Term]
id: DPBO:0002000
name: alias
def: "Unique identificator for a study. This is used to link experiments to the study." []

[Term]
id: DPBO:0002001
name: study abstract
def: "Briefly describes the goals, purpose, and scope of the Study.  This need not be listed if it can be inherited from a referenced publication." []

[Term]
id: DPBO:0002002
name: title
def: "Title of the study as would be used in a publication." []

[Term]
id: DPBO:0002005
name: project name
def: "Name of the project within which the experiment was organized." []

[Term]
id: DPBO:0002006
name: sequencing method
def: "Sequencing method used; e.g. Sanger, pyrosequencing, ABI-solid." []

[Term]
id: DPBO:0002007
name: investigation type
def: "Nucleic Acid Sequence Report is the root element of all MIxS compliant reports as standardized by Genomic Standards Consortium" []
```

**Comment by kdumschott** [comment]
@Hannah-Doerpholz has suggested the following xrefs:

- alias = ARC_00000120 (identifier, but not specific to study, can also be investigation identifier etc)
- study abstract = ARC_00000116 (description, but also not study specific, could also be assay or investigation description)
- title = ARC_00000126 (title, as publication title) OR ARC_00000131 (name, as this might be study name; doesn't have to be the publication title though)
- project name = no equivalent for the definition
- sequencing method = not part of the ARC container ontology as it is project-specific (to sequencing projects)
- investigation type = maybe ARC_00000116 (description) too, but there is no such thing as investigation type in the ARC specification

Some fit better than others, and none of the dpbo terms listed above have an exact equivalent in the ARC ontology, so I am not certain if linking the terms is the best way forward, but we are open to feedback.

**Comment by Hannah-Doerpholz** [comment]
Since the terms are not actually identical to anything we have in the ARC ontology when it comes to the details of the description we chose to keep the terms in DPBO and not link them. But if you feel that this is not suitable feel free to re-open the issue and let us know
