### ISSUE TITLE
[Import Ontology] 

### ISSUE THREAD

**Issue by SabrinaZander** [nfdi4plants/nfdi4plants_ontology#65]
### Ontology
Ontology of Microbial Phenotypes 
https://www.ebi.ac.uk/ols/ontologies/omp

### Please state the reason to import this ontology into the SwateDB

To annotate data in SFB1535 MibiNet and to generate Swate Templates

**Comment by kdumschott** [comment]
Hello,

Do you know if there is an OBO file available for this ontology? I can only find OWL format.

**Comment by SabrinaZander** [comment]
Hello,
I don't know if this link might help?
https://github.com/microbialphenotypes/OMP-ontology
There is a file called omp.obo but I have no idea if that is the correct file ;-)
