### ISSUE TITLE
[NTR] biolistic transformation - synonym: particle bombardment

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants_ontology#68]
### New term name

biolistic transformation

### Definition

A method for physical delivery of DNA (likely also RNA) into cells. Gold or tungsten particles are coated with DNA and shot with a gene gun / particle gun on tissue like leaves, seedlings, callus or other types of tissue and cells. Often, in plant sciences, this method is used as a transient transformation method in protein or protein-protein interaction localization studies using binary vectors. Co-transformation of multiple vectors is possible. 

Definition source: previous lab routine, used in various projects and own publications, maintenance of a respective lab device and introductions to it for multiple years.

### Synonyms

particle bombardment

### Your ORCID

https://orcid.org/0000-0002-3879-7057

**Comment by kdumschott** [comment]
Thank you for your suggestion, your term has been added to dpbo.
