### ISSUE TITLE
[NTR] transformation protocol

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants_ontology#69]
### New term name

transformation protocol

### Definition

A protocol describing a transformation method of cell, tissues or organisms. It can be differentiated into a transient transformation protocol and a stable transformation protocol. Examples are biolistic tranformation for the transient version and agrobacterium mediated plant tranformation e.g. following the floral dip method (Clough and Bent, 1998) for the stable version yielding a genetically transformed organism with respective (segregating) offspring. 

Please note: transient and stable transformation protocol are no synonyms but rather required to differentiate both. However, both (=child term to the following) are transformation protocols (=parent term).

Definition source: Own lab routins for more than a decade and publications. 
For the mentioned floral dip method:
Clough SJ, Bent AF. Floral dip: a simplified method for Agrobacterium-mediated transformation of Arabidopsis thaliana. Plant J. 1998 Dec;16(6):735-43. doi: 10.1046/j.1365-313x.1998.00343.x. PMID: 10069079.

### Your ORCID

https://orcid.org/0000-0002-3879-7057

**Comment by kdumschott** [comment]
Hi Andrea,

If you would like to give definitions for the transient and stable protocols, I can add them as child terms.
