### ISSUE TITLE
[NTR] bioimaging protocol

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants_ontology#70]
### New term name

bioimaging protocol

### Definition

A protocol describing the method of a bioimaging technique. Bioimaging is a biological imaging method causing as minimal interference to living processes as possible or getting a 3-D structure from the outside without physical interference e.g. of cells, tissues or other living matter. Usually, the method is non-invasive but also fixed biological material is covered by a wider definition. (adapted from https://cab.ku.dk/what_is_bioimaging/) 

### Your ORCID

https://orcid.org/0000-0002-3879-7057

**Comment by kdumschott** [comment]
Thank you for your contribution, your term has been added to DPBO.
