### ISSUE TITLE
[NTR] light duration

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#75]
### New term name

light duration

### Definition

"The time (e.g. hours of light) of the light regime in a growth experiment (e.g. 12hr light /12hr dark, 12/12, short day, long day)"

> taken from: DPBO:0000041 - growth day length

### Synonyms

id: DPBO:0000041
name: growth day length

### Xrefs

http://purl.obolibrary.org/obo/ZECO_0000147

**Comment by kdumschott** [comment]
Hi, As the term 'growth day length' has already been identified as a synonym for 'light duration', I suggest adding 'light duration' as a synonym of 'growth day length' instead of making it its own term.
