### ISSUE TITLE
[Missing ontology] EFO - Experimental Factor Ontology

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/nfdi4plants_ontology#8]
Ontology is available at: <http://www.ebi.ac.uk/efo/efo.owl>

#### Reasons for this addition

Covers some lab protocol concepts in addition to / not well covered by PECO
- EFO_0000634: Organism
- EFO_0000635: Organism part
- EFO_0000513: Genotype
- EFO_0000246: age
- EFO_0000724: time point

**Comment by kdumschott** [comment]
https://www.ebi.ac.uk/efo/efo.obo has been added to the ext_ontologies.include list and will now be added to SwateDB
