### ISSUE TITLE
A Term for "published" related to the status of a publication

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#85]
### Type of Issue

- [ ] Report a Bug
- [ ] Report a Typo or Error
- [ ] Feature Request
- [X] Help or Question

### Comments

I am currently working on the Swate metadata forms and wanted to add the "published" status to a publication found online via DOI or PMID.

https://github.com/nfdi4plants/Swate/issues/372

**Comment by StellaEggels** [comment]
The environmental factor ontology is included in Swate and includes the term "published" (EFO:0001796; Publication published in a journal) as well as "publication status".

**Comment by Freymaurer** [comment]
Perfect! Thanks a lot! I will add this to the swate form
