### ISSUE TITLE
[Feature Request]: Need UNIMOD obo

### ISSUE THREAD

**Issue by frsommer** [nfdi4plants/nfdi4plants_ontology#92]
### Contact Details

frsommer@rptu.de

### Is your feature request related to a problem?

I love SWATE and ARCitect/commander but
when specifying Protein or peptide modifications there is no cool obo. UNIMOD.org might be the right one:
https://www.unimod.org/downloads.html
obo: https://www.unimod.org/obo/unimod.obo

so I could describe the search-modifications considered like UNIMOD:3
![image](https://github.com/user-attachments/assets/d94013ec-f3f6-4034-aa8e-1337f7e75017)

a problem here is that sometimes not all "Specifity Definitions" are considered which are listed unter this term UNIMOD:3 but e.g. only definition 1 is considered

If there could be a description like "Biotin K, Unimod:3" for specifying only definition 1 that would be an add-on! 
might think of putting the UNIMOD as unit (which would be "3" then) and add the residues where it is occuring?

but having the unimod obo might be already good

### Describe the solution you would like!

see above:
minimal: add unimod obo
optional: add definition selection and PSI-Name or / and residue as definition

i dont think thee are better obos uniprot is anyway linked to MascotServer etc.

### Host

Applies to All

### Host Details

any

**Comment by StellaEggels** [comment]
Hi, we currently already have the protein modification ontology (PSI-MOD) included in Swate but I understand that this is not sufficient? 
If we add the UNIMOD obo file the following information would be available in Swate: the ID (e.g. UNIMOD:3, in the TSR/TAN columns), the name (e.g. Biotin) and the definition (e.g. Biotinylation). If you need additional information we would have to modify the obo file. What is the exact information you need? Is it all information listed under specificity definition 1 and 2 or only the respective Site? And in what way would you need the information in Swate, can you give me an example of your column header and of a filled cell of that column?

**Comment by frsommer** [comment]
Hi,
Sorry for the late reply, I just now find the  time to go on with this.

I specifically checked the PSI-MOD and found it actually contains all specifications I need (as far as I can see).

Now digging even deeper in the OLS I can also find Sum-formula and difference mass for the modifications, and all the other things I was missing …

Sorry for bothering you, I just had a hard time to find the terms specific to my modifications in the Swate search tool.
Could you please close the case?
Best
frederik

**Comment by HLWeil** [comment]
Ah, just now had to annotate some modification Terms and remembered this issue. Glad it has been resolved, I too found was I was looking for.
