### ISSUE TITLE
[Import term] Infinte M200 plate reader (Tecan)

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants_ontology#93]
### Term name and id

Infinte M200 plate reader (Tecan) (BAO_0000726), if the "(Tecan)" in brackets is problematic maybe move to the beginning in DPBO

### Term link

https://ontobee.org/ontology/BAO?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0150076

### Parent term(s)

Maybe we could also include "microplate reader" (https://ontobee.org/ontology/MMO?iri=http://purl.obolibrary.org/obo/MMO_0000714) as parent

### Your ORCID

0000-0003-1945-6342

**Comment by StellaEggels** [comment]
Infinite M200 plate reader (Tecan) was added to  DPBO (DPBO:0000116)
