### ISSUE TITLE
[NTR] Stone mortar and pestle

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants_ontology#96]
### New term name

Stone mortar and pestle

### Definition

Combination of two tools used to grinding or shearing substances to a fine paste or powder.

### Parent term(s)

Add "grinding device"?

### Your ORCID

0000-0003-1945-6342

**Comment by StellaEggels** [comment]
mortar and pestle (DPBO:0000118), as well as grinding device (DPBO:0000119) were added to DPBO
