### ISSUE TITLE
[NTR] sugar measurement 

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants_ontology#97]
### New term name

sugar measurement

### Definition

The quantification of some sugar.

### Parent term(s)

https://www.ebi.ac.uk/ols4/ontologies/efo/classes?short_form=EFO_0004998

### Your ORCID

0000-0003-1945-6342

**Comment by StellaEggels** [comment]
sugar measurement was added to DPBO (DPBO:0000120)
