### ISSUE TITLE
[NTR] TAP-NH4 medium for the growth of Chlamydomonas

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/nfdi4plants_ontology#98]
### New term name

TAP Medium

### Definition

Hello fellow ARC-fans,
it would be great to implement TAP-NH4 medium for the growth of Chlamydomonas as an ontolgy term. You can find it at: https://cshprotocols.cshlp.org/content/2006/1/pdb.rec560.full?sid=64b6efaf-4059-496d-9b9a-541b344bf2cb. The doi is: doi:10.1101/pdb.rec560. This is from Cold Spring Harbor Protocols. Might me cool to integrate even more protocols/ growth media?

(Ticket via helpdesk)

**Comment by StellaEggels** [comment]
Thanks for your contribution, TAP medium was added to DPBO. If you would like other growth media to be added feel free to suggest them as well.
